#!/bin/bash
##
# @Description: Train and/or run conversational AI model.
# Accepts multiple arguments
# API

I='Intents'
R='Responses'

PORT=9000
ACTION=reactions
RESPONSE_SERVER=1
ENDPOINT=config/endpoints.yml
LOGFILE=logs/dialog.log
RUNYN=n

source env/env.sh

# args here are really just class @property's
function show_usage (){
    printf "Usage: $0 [options [parameters]]\n"
    printf "\n"
    printf "Options:\n"
    printf " -t|--train [target], Train model (nlu, dialogue or both)\n"
    printf " -r|--run [model], Run the specified model \n"
    printf " -d|--debug, Run in debug mode\n"
    printf " -m|--model, Name of model to run (aka domain)\n"
    printf " -e|--epochs, Unless you have infinite patience\n"
    printf " -a|--enable-api, Enables web api\n"
    printf " -h|--help, Print help\n"
return 0
}
if [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]];then
    show_usage
fi

function get_train_target (){
  case "$1" in
    nlu|intent|intents)
      shift
      CHOICE=1
      echo "Training nlu (intents)"
      ;;
    dialog|dialogue|response)
      shift
      CHOICE=2
      echo "Training dialogue (responses)"
      ;;
    both)
      shift
      CHOICE=3
      echo "Training nlu and dialog models (intents and responses)"
      ;;
    *)
      ask_train_target "$@"
  esac
  return 0
}

function ask_train_target (){
if [[ -z "${1}" ]]; then
  echo "Train Intent Recognition or Dialogue Response?
  1. train nlu (intents)
  2. train dialogue (responses)
  3. train both"
  read CHOICE
fi
}

function ask_run_app (){
  echo "Run app after training model? (y/n or press 'd' to run in debug mode)"
  read RUNYN
}

function check_valid_model (){

  if [[ $1 == scheduler ]]; then
    return 0
  else
    echo "Sorry, this version only supports the scheduler domain."
    return 0
  fi
}

# And we get our command args...
while [ ! -z "$1" ]; do
  case "$1" in
     --debug|-d)
      RUNYN=d
      ;;
     --train|-t)
      shift
      TRAIN=true
      get_train_target "$@"
      ;;
     --run|-r)
      if [[ $RUNYN != d ]]; then
        RUNYN=y
      fi
      ;;
     --model|-m)
      # shift
      check_valid_model "$@"
      ;;
     *)
      show_usage
      ;;
  esac
shift
done

# @TODO - make this a select list, with option to create new project/model.
if [[ -z "${BOT_DOMAIN}" ]]; then
  #echo "length is ${#BOT_DOMAIN}"
  read -p "No active model set. Enter model to use or press 'Enter' for [default]: " PROJECT
  PROJECT=${PROJECT:-default}
else
  #read -p "Enter model to use or enter for [$BOT_DOMAIN]: " PROJECT
  echo "Active model is for the [$BOT_DOMAIN] domain. "
  PROJECT=${PROJECT:-$BOT_DOMAIN}
fi

# @Todo: rename CHOICE to TRAIN_TARGET
if [[ $TRAIN == true ]] && [[ -z "${CHOICE}" ]]; then
  ask_train_target
fi

# @TODO: Either change RUNYN to RUN or change TRAIN to TRAIN_Y_N
# if [[ -z "${RUNYN}" ]]; then
#  ask_run_app
# fi

# Check if domain.yml exists and vanquish.
mv domain.yml .domain.yml.prev
ln -s domain/$PROJECT/domain.yml domain.yml

# Active vs. Current
cd domain
mv stories.md .stories.md.prev
ln -s $PROJECT/stories/stories.md stories.md
cd - > /dev/null
cd models
mv current .current.prev
ln -s $PROJECT current
cd - > /dev/null
echo "$PROJECT is now the current model"
DOMAIN=$PROJECT

# Tell them what we're doing.
case $CHOICE in
        [1]* ) echo "Ready to train model: '" $PROJECT "' for Intent Extraction";;
        [2]* ) echo "Ready to train model: '" $PROJECT "' for Response Logic";;
        [3]* ) echo "Ready to train model: '" $PROJECT "' for both Intent and Response Logic";;
esac

yn=y
while true; do
    break
    read -p "Continue?" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer y or n.";;
    esac
done

# create model directory if it doesn't exist

if [[ $RUNYN = 'y' ]]; then
  REACTION="domain.$PROJECT.$ACTION"
  python -m rasa_core_sdk.endpoint --actions $REACTION & echo $!
fi

## "Let's git down to bizniz." -overheard in the office.
## NB. switches should use '-' not '_'
if [[ -z "${CHOICE}" ]] && [[ $RUNYN = 'y' ]]; then
  echo "Let's do this! (no training, running model)";
  # check training data exists
  # python -m rasa_nlu.train -c nlu_config.yml --data data/$PROJECT/intents/nlu_data.md -o models --fixed_model_name nlu --project $PROJECT --verbose ;
  # python -m rasa_nlu.train -c config.yml --data data//$PROJECT/intents -o models --fixed_model_name nlu --project $PROJECT --verbose --path agent ;
  #time python -m rasa_nlu.train -c config.yml --data data//$PROJECT/intents -o models --fixed_model_name nlu --project $PROJECT --verbose ;
  python -m rasa_core.run \
    -u models/scheduler/nlu \
    -d models/scheduler/dialogue \
    --endpoints $ENDPOINT \
    --log_file $LOGFILE
fi

if [[ -z "${CHOICE}" ]] && [[ $RUNYN = 'd' ]]; then
  echo "Let's do this! (running model in debug mode)";
  # check training data exists
  # python -m rasa_nlu.train -c nlu_config.yml --data data/$PROJECT/intents/nlu_data.md -o models --fixed_model_name nlu --project $PROJECT --verbose ;
  # python -m rasa_nlu.train -c config.yml --data data//$PROJECT/intents -o models --fixed_model_name nlu --project $PROJECT --verbose --path agent ;
  #time python -m rasa_nlu.train -c config.yml --data data//$PROJECT/intents -o models --fixed_model_name nlu --project $PROJECT --verbose ;
  # python -m rasa_core_sdk.endpoint --actions $ACTION & echo $!
  python -m rasa_core.run -d models/$PROJECT/dialogue -u models/$PROJECT/nlu --endpoints $ENDPOINT --log_file $LOGFILE --debug
fi

# train nlu only
if [[ $CHOICE == 1 && $RUNYN = 'n' ]]; then
  echo "Training $I for the domain:";
  echo $PROJECT | tr '[:lower:]' '[:upper:]'
  # check training data exists
  time python -m rasa_nlu.train -c config.yml --data domain/$DOMAIN/intents -o models --fixed_model_name nlu --project $PROJECT --verbose ;
fi

# train nlu and run
if [[ $CHOICE == 1 && $RUNYN = 'y' ]]; then
  echo "Training $I, then running app for the domain:";
  echo $PROJECT | tr '[:lower:]' '[:upper:]'
  # check training data exists
  time python -m rasa_nlu.train -c config.yml --data domain/$DOMAIN/intents -o models --fixed_model_name nlu --project $PROJECT --verbose ;
  python -m rasa_core.run -d models/$PROJECT/dialogue -u models/$PROJECT/nlu --endpoints $ENDPOINT --log_file $LOGFILE
fi

# train nlu and run in debug mode
if [[ $CHOICE == 1 && $RUNYN = 'd' ]]; then
  echo "Training $I, then debugging app for the domain:";
  echo $PROJECT | tr '[:lower:]' '[:upper:]'
  # check training data exists
  time python -m rasa_nlu.train -c config.yml --data domain/$DOMAIN/intents -o models --fixed_model_name nlu --project $PROJECT --verbose ;
  python -m rasa_core.run -d models/$PROJECT/dialogue -u models/$PROJECT/nlu --endpoints $ENDPOINT --log_file $LOGFILE --debug
fi

# train dialogue only
if [[ $CHOICE == 2 && $RUNYN = 'n' ]]; then
  echo "Ttraining $R for the domain.";
  echo $PROJECT | tr '[:lower:]' '[:upper:]'
  # directory check, make directory if needed
  time python -m rasa_core.train -d domain.yml -s domain/$DOMAIN/stories/stories.md -o models/$PROJECT/dialogue -c policies.yml;
fi

# train dialogue and run
if [[ $CHOICE == 2 && $RUNYN == 'y' ]]; then
  echo "Training $R, then running app for the domain:";
  echo $PROJECT | tr '[:lower:]' '[:upper:]'
  time python -m rasa_core.train -d domain.yml -s domain/$DOMAIN/stories/stories.md -o models/$PROJECT/dialogue -c policies.yml;
  python -m rasa_core.run -d models/$PROJECT/dialogue -u models/$PROJECT/nlu --endpoints $ENDPOINT --log_file $LOGFILE
fi

# train dialogue and run in debug mode
if [[ $CHOICE == 2 && $RUNYN == 'd' ]]; then
  echo "Training $R, then debugging app for the domain:";
  echo $PROJECT | tr '[:lower:]' '[:upper:]'
  time python -m rasa_core.train -d domain.yml -s domain/$DOMAIN/stories/stories.md -o models/$PROJECT/dialogue -c policies.yml;
  python -m rasa_core.run -d models/$PROJECT/dialogue -u models/$PROJECT/nlu --endpoints $ENDPOINT --log_file $LOGFILE --debug
fi

# train both nlu and dialogue
if [[ $CHOICE == 3 && $RUNYN == 'n' ]]; then
  # PROJECT=${PROJECT^^} # Don't assume bash 4+
  echo "Training $I and $R for the domain:";
  echo $PROJECT | tr '[:lower:]' '[:upper:]'
  time python -m rasa_nlu.train -c config.yml --data domain/$DOMAIN/intents -o models --fixed_model_name nlu --project $PROJECT --verbose ;
  time python -m rasa_core.train -d domain.yml -s domain/$DOMAIN/stories/stories.md -o models/$DOMAIN/dialogue -c policies.yml;
fi

# train both and run
if [[ $CHOICE == 3 && $RUNYN == 'y' ]]; then
  echo "Training both $I and $R, then running app for the domain:";
  echo $PROJECT | tr '[:lower:]' '[:upper:]'
  time python -m rasa_nlu.train -c config.yml --data domain//$DOMAIN/intents -o models --fixed_model_name nlu --project $PROJECT --verbose ;
  time python -m rasa_core.train -d domain.yml -s domain/$DOMAIN/stories/stories.md -o models/$PROJECT/dialogue -c policies.yml;
  python -m rasa_core.run -d models/$PROJECT/dialogue -u models/$project/nlu --endpoints $ENDPOINT --log_file $LOGFILE
fi

# train both and run in debug mode
if [[ $CHOICE == 3 && $RUNYN == 'd' ]]; then
  echo "Training both $I and $R, then debugging app for the domain:";
  echo $PROJECT | tr '[:lower:]' '[:upper:]'
  # directory check, make directory if needed
  time python -m rasa_nlu.train -c config.yml --data domain/$DOMAIN/intents -o models --fixed_model_name nlu --project $PROJECT --verbose ;
  time python -m rasa_core.train -d domain.yml -s domain/$DOMAIN/stories/stories.md -o models/$PROJECT/dialogue -c policies.yml;
  python -m rasa_core.run -d models/$PROJECT/dialogue -u models/$PROJECT/nlu --endpoints $ENDPOINT --log_file $LOGFILE --debug
fi


# No Dragons Beyond This Point.
kill $!
