facebook:
  verify: "rasa-bot"
  secret: "<FACEBOOK SECRET>"
  page-access-token: "<FACEBOOK PAGE TOKEN>"


slack:
  slack_token: "<SLACK AUTH TOKEN>"
  slack_channel: "<SLACK CHANNEL ID>"
  proxy: "http://myProxy.online"  # Proxy Server to route your traffic through. (optional.)
  slack_retry_reason_header: "x-slack-retry-reason"  # Slack HTTP header name indicating reason that slack send retry request. This configuration is optional.
  slack_retry_number_header: "x-slack-retry-num"  # Slack HTTP header name indicating the attempt number. This configuration is optional.
  errors_ignore_retry: None  # Any error codes given by Slack included in this list will be ignored. Error codes are listed [here](https://api.slack.com/events-api#errors).
  use_threads: False  # If set to True, bot responses will appear as a threaded message in Slack. This configuration is optional and set to False by default.


twilio:
  account_sid: "<TWILIO ACCOUNT ID>"
  auth_token: "<TWILIO AUTH TOKEN>"
  twilio_number: "whatsapp:<TWILIO NUMBER>"


whatsapp:
  # cf. https://medium.com/@alfredfranciz/integrate-rasa-with-whatsapp-1b1477b51090
